### ISSUE TITLE
Markdown should be rendered when rendering place description

### ISSUE THREAD

**Issue by dtinth** [noobdevth/tech-events-browser#3]
Recent commits added more rich information to the location data:

- Location can now have a URL (in `event.location.url`, which points to a Google Maps URL).
- Extended description for location can contain Markdown. (*)

Right now, the tech-events-browser does not render markdown when displaying the description:

![image](https://user-images.githubusercontent.com/193136/34649545-d99ea7ec-f3e3-11e7-92c5-41eed71b1b1d.png)

**Comment by heypoom** [comment]
Oh, okay! I'll add the Markdown renderer to the location fields. Thanks for letting me know.

**Comment by heypoom** [comment]
I added the Markdown renderer to `location.title` and `location.detail`. This should be okay, for now.

<img width="1051" alt="screenshot 2018-01-07 21 53 26" src="https://user-images.githubusercontent.com/4714175/34650535-494fa300-f3f5-11e7-9204-bd60ff8c319b.png">

**Comment by dtinth** [comment]
@phoomparin Saw the commit 343556c68f409f80b9fcac74e668af3e2c2b819c

To be clear, `location.title` does not contain Markdown. But it may be linked by means of `location.url`.

It’s `location.description` that may contain Markdown :)

**Comment by heypoom** [comment]
Oops, my bad. 8d48219d648f67aaf186042853ed031452fd87f5 should do it.

<img width="888" alt="screenshot 2018-01-07 22 29 21" src="https://user-images.githubusercontent.com/4714175/34650863-57afa580-f3fa-11e7-81e3-9768f802f0e6.png">

**Comment by dtinth** [comment]
Nice!

The plan on my side is to have the “Location” URL always be a Google Maps URL. So should be simple to integrate with Google Maps API.

Closing as fixed. Thanks! 😄
