### ISSUE TITLE
Show Google Maps in the Event Card

### ISSUE THREAD

**Issue by heypoom** [noobdevth/tech-events-browser#4]
As @dtinth noted that every location URLs will always be a Google Maps URL, so it should be trivial to show Google Maps directly on the event card.

**Comment by MicroBenz** [comment]
Maybe I can help on this one? If yes. What about API_KEY for Google Maps?

**Comment by dtinth** [comment]
Ping @phoomparin

**Comment by MicroBenz** [comment]
Any update?

**Comment by heypoom** [comment]
Oh, sorry! I was a bit busy. Perhaps we could store the API key in the environment variables, and then I might provide my own key for production deployment. For now, you could supply your own key when developing.

Thanks! 🏆

**Comment by MicroBenz** [comment]
So where did you keep environment variables? Because I try to create `.env.local` and `.env`. Both aren't work

And here is a screenshot of how Maps appear on card
![image](https://user-images.githubusercontent.com/9103800/35194533-bc8e0706-fee7-11e7-82a9-df09f118826c.png)

**Comment by dtinth** [comment]
@MicroBenz `.env` files doesn’t seem to be supported in `react-static`, but [all environment variables are available in build time.](https://github.com/nozzle/react-static/blob/e4bdd37cdcd1170f968bd5134ab999997aae1e45/src/webpack/webpack.config.prod.js#L46). You just need to make sure that the environment variable is present when you run `react-static`.

You can do one of these:

1. Specify environment variables on the shell.

2. Adjust the config file to load the environment variables using e.g. [`dotenv` npm package](https://www.npmjs.com/package/dotenv).

**Comment by heypoom** [comment]
Closed by #8
